### PR TITLE
Bump containerd to 1.5.2

### PR DESCRIPTION
**Pull request by aledbf**
Upgrade containerd to 1.5.2

Signed-off-by: Manuel Alejandro de Brito Fontes aledbf@gmail.com

### CODE REVIEW

**Comment by estesp** [comment]
This commit needs updated with a `Signed-off-by:` line to pass the CI checks. Thanks!

**Comment by aledbf** [comment]
@estesp done

**Review by estesp — APPROVED** [review]
LGTM

**Review by dims — APPROVED** [review]
LGTM

**Pull request merged**
