### PR TITLE
make plugins/ulimit-adjuster a separate module

### PR DESCRIPTION
**Pull request by thaJeztah**
Also switch it to use the new log module, instead of depending on containerd

### CODE REVIEW

**Review by klihub — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
@samuelkarp @estesp ptal ☺️

**Review by samuelkarp — APPROVED** [review]
Thanks @thaJeztah!

**Comment by thaJeztah** [comment]
Thanks! I'll rebase the other one, and then we can look if that's a good way forward to cut the circular dependency (at least for this module that is)

**Pull request merged**
