### PR TITLE
add sandbox Annotations to NRI Request

### PR DESCRIPTION
**Pull request by sctb512**
Currently, containerd only passes `pod.Labels` to the NRI (v0.1.0) plugin, but not `pod.Annotations`. In some situations we prefer to set `Pod.Spec.Annotations` instead of `Pod.Spec.Labels`.

This PR provides support for passing sandbox annotations to the NRI plugin.

Related to #59

### CODE REVIEW

**Comment by samuelkarp** [comment]
I'm not sure if we want to add new functionality to the 0.1.x series here.  The release/0.1 branch was really created just for dependency cleanup.

**Comment by sctb512** [comment]
> I'm not sure if we want to add new functionality to the 0.1.x series here. The release/0.1 branch was really created just for dependency cleanup.

Should we create a new branch to add new features to `v0.1.0`? The `v0.1.0` is now the main product version, which was integrated with containerd 1.6.x.

**Comment by samuelkarp** [comment]
> Should we create a new branch to add new features to v0.1.0?

I don't know if we want to add new features to v0.1.x.

> The v0.1.0 is now the main product version, which was integrated with containerd 1.6.x.

It's not clear whether we'd want to incorporate this into containerd 1.6.  containerd 1.6 is an [LTS](https://containerd.io/releases/#support-horizon) with some limited exceptions for adding new features, but:

> LTS releases can also accept feature backports to support new Kubernetes releases. The default action has to be reject it though, for long-term stability. This is still negotiable when the feature is a hard dependency for a new release of Kubernetes.

This change does not appear to be a hard dependency for a new release of Kubernetes.

**Comment by sctb512** [comment]
> This change does not appear to be a hard dependency for a new release of Kubernetes.

Yes, it's not a hard dependency for a new release of Kubernetes. 

However, the NRI for containerd 1.7.x has been redesigned. So, it seems hard to add new features to NRI v0.1.x. Perhaps updating containerd to 1.7.x is the only way to use the new features of NRI?

**Comment by samuelkarp** [comment]
> Perhaps updating containerd to 1.7.x is the only way to use the new features of NRI?

Yes

**Comment by sctb512** [comment]
> > Perhaps updating containerd to 1.7.x is the only way to use the new features of NRI?
> 
> Yes

Got it. Thanks.

**Pull request closed without merging**
