### PR TITLE
Reset source path of api.pb.go to pkg/api/api.proto

### PR DESCRIPTION
**Pull request by zxj874478410**
Source path of api.pb.go is changed in #94 . This changes the variable naming in the file. 
Tix this by regenerate api.proto.

### CODE REVIEW

**Comment by zxj874478410** [comment]
It's my fault for changing the file generation path...pls @klihub @mikebrow

**Review by mikebrow — CHANGES_REQUESTED** [review]
wave .. it happens.. :) 

My bad, I didn't open the proto generated file to look over / review the diff.. 

Also the versioning for your build is off as set by the makefile helpers

https://github.com/containerd/nri/pull/94/files#diff-344492a28bbcb6eda633fc9255eaed8729b3076abd04bd05c4626bf25f7a10d6L18-R20

FYI these are the versions being used by containerd .. protobuf version v3.20.1 and protoc v1.28.0 

https://github.com/containerd/nri/blob/main/scripts/install-protobuf#L23
https://github.com/containerd/nri/blob/main/Makefile#L188

**Comment by zxj874478410** [comment]
> wave .. it happens.. :)
> 
> My bad, I didn't open the proto generated file to look over / review the diff..
> 
> Also the versioning for your build is off as set by the makefile helpers
> 
> https://github.com/containerd/nri/pull/94/files#diff-344492a28bbcb6eda633fc9255eaed8729b3076abd04bd05c4626bf25f7a10d6L18-R20
> 
> FYI these are the versions being used by containerd .. protobuf version v3.20.1 and protoc v1.28.0
> 
> https://github.com/containerd/nri/blob/main/scripts/install-protobuf#L23 https://github.com/containerd/nri/blob/main/Makefile#L188

Fixed withprotobuf version v3.20.1 and protoc v1.28.0 :)

**Review by mikebrow — APPROVED** [review]
LGTM

**Comment by klihub** [comment]
> It's my fault for changing the file generation path...pls @klihub @mikebrow

@zxj874478410 Normally, you should not need to do manually proto-compile anything. The Makefile has the necessary dependencies and targets to automatically proto-compile if the proto-file changes. The plugins don't get recompiled in that case without a `make clean`, but the compiled proto files do...

**Review by klihub — APPROVED** [review]
LGTM

**Pull request merged**
